// ==============================================================================
// SehatPass: Standalone Public Emergency Web App Client Script
// ==============================================================================
// 1. Reads opaque emergency token from window.location.search (?token=...)
// 2. Invokes the Supabase emergency-access Edge Function with ?format=json
// 3. Securely constructs DOM elements using textContent (Strict XSS Prevention)
// 4. Handles loading, profile, invalid, revoked, missing, and network error states
// 5. Zero credentials stored; zero patient data logged to console or storage
// ==============================================================================

(function () {
  "use strict";

  // Authoritative Supabase emergency-access API endpoint
  const API_ENDPOINT =
    "https://vnavceiizdjekbmtzpsn.supabase.co/functions/v1/emergency-access";

  // DOM Elements
  const loadingState = document.getElementById("loading-state");
  const errorState = document.getElementById("error-state");
  const profileState = document.getElementById("profile-state");

  const errorIcon = document.getElementById("error-icon");
  const errorTitle = document.getElementById("error-title");
  const errorDesc = document.getElementById("error-desc");

  const patientName = document.getElementById("patient-name");
  const patientGender = document.getElementById("patient-gender");
  const patientDob = document.getElementById("patient-dob");
  const patientMetaDot = document.getElementById("patient-meta-dot");
  const bloodGroupVal = document.getElementById("blood-group-val");

  const contactName = document.getElementById("contact-name");
  const contactRel = document.getElementById("contact-rel");
  const contactPhoneDisplay = document.getElementById("contact-phone-display");
  const btnCallEmergency = document.getElementById("btn-call-emergency");
  const contactAction = document.getElementById("contact-action");
  const noContactNotice = document.getElementById("no-contact-notice");

  const allergiesVal = document.getElementById("allergies-val");
  const conditionsVal = document.getElementById("conditions-val");
  const medicinesList = document.getElementById("medicines-list");
  const noMedicinesNotice = document.getElementById("no-medicines-notice");
  const reportsList = document.getElementById("reports-list");
  const noReportsNotice = document.getElementById("no-reports-notice");
  const reportsErrorNotice = document.getElementById("reports-error-notice");
  const verificationTimestamp = document.getElementById("verification-timestamp");

  /**
   * Validates that a URL is a secure HTTPS URL from trusted backend.
   * Rejects javascript:, data:, file:, http:, and malformed strings.
   */
  function isValidHttpsUrl(urlString) {
    if (!urlString || typeof urlString !== "string") return false;
    const trimmed = urlString.trim();
    if (!trimmed.toLowerCase().startsWith("https://")) return false;
    try {
      const parsed = new URL(trimmed);
      return parsed.protocol === "https:";
    } catch (_) {
      return false;
    }
  }

  /**
   * Helper to format report category for display.
   */
  function getCategoryBadge(category) {
    if (!category) return "";
    const lower = category.toLowerCase();
    if (lower === "bloodtest" || lower === "blood_test") return "Blood Test";
    if (lower === "scan") return "Scan";
    return "";
  }

  /**
   * Switches active UI state between 'loading', 'profile', and 'error'.
   */
  function switchState(stateName) {
    loadingState.classList.remove("active");
    errorState.classList.remove("active");
    profileState.classList.remove("active");

    if (stateName === "loading") {
      loadingState.classList.add("active");
    } else if (stateName === "profile") {
      profileState.classList.add("active");
    } else if (stateName === "error") {
      errorState.classList.add("active");
    }
  }

  /**
   * Renders specific error views for invalid, inactive, or missing tokens.
   */
  function renderError(type, customMsg) {
    switchState("error");
    errorIcon.className = "error-icon";

    if (type === "missing_token") {
      errorIcon.textContent = "🔍";
      errorIcon.classList.add("amber");
      errorTitle.textContent = "No Emergency Token Provided";
      errorDesc.textContent =
        "Please scan an official SehatPass Emergency QR code to view a patient's emergency medical profile.";
    } else if (type === "invalid_token") {
      errorIcon.textContent = "⚠️";
      errorIcon.classList.add("amber");
      errorTitle.textContent = "Invalid Emergency Token";
      errorDesc.textContent =
        customMsg ||
        "The scanned QR token is malformed, unrecognized, or invalid. Please ensure the QR code was generated by SehatPass.";
    } else if (type === "inactive_token") {
      errorIcon.textContent = "🔒";
      errorTitle.textContent = "Emergency Access Inactive";
      errorDesc.textContent =
        customMsg ||
        "This emergency profile has been deactivated, revoked, or regenerated by the patient. The medical details for this QR token are no longer accessible.";
    } else {
      errorIcon.textContent = "⚙️";
      errorTitle.textContent = "Temporary Service Notice";
      errorDesc.textContent =
        customMsg ||
        "Unable to retrieve emergency records at this time. Please check your internet connection or verify with emergency personnel.";
    }
  }

  /**
   * Securely binds patient data to the DOM.
   */
  function renderProfile(data) {
    // 1. Patient Identification
    patientName.textContent = data.full_name || "Patient Name Hidden";

    const gender = data.gender || "";
    const dob = data.date_of_birth || "";

    if (gender) {
      patientGender.textContent = gender;
      patientGender.style.display = "inline";
    } else {
      patientGender.style.display = "none";
    }

    if (dob) {
      patientDob.textContent = `DOB: ${dob}`;
      patientDob.style.display = "inline";
    } else {
      patientDob.style.display = "none";
    }

    if (gender && dob) {
      patientMetaDot.style.display = "inline";
    } else {
      patientMetaDot.style.display = "none";
    }

    if (!gender && !dob) {
      patientGender.textContent = "Demographics not specified";
      patientGender.style.display = "inline";
    }

    // Blood Group
    bloodGroupVal.textContent = data.blood_group || "N/A";

    // 2. Emergency Contact
    const contact = data.emergency_contact;
    if (contact && (contact.name || contact.phone)) {
      contactName.textContent = contact.name || "Emergency Contact";
      contactRel.textContent = contact.relationship || "Contact";

      if (contact.phone && contact.phone.trim().length > 0) {
        const cleanPhone = contact.phone.trim();
        contactPhoneDisplay.textContent = cleanPhone;
        contactPhoneDisplay.style.display = "block";
        btnCallEmergency.href = `tel:${encodeURIComponent(cleanPhone)}`;
        contactAction.style.display = "block";
        noContactNotice.style.display = "none";
      } else {
        contactPhoneDisplay.style.display = "none";
        contactAction.style.display = "none";
        noContactNotice.style.display = "block";
      }
    } else {
      contactName.textContent = "No Contact Listed";
      contactRel.textContent = "Not provided by patient";
      contactPhoneDisplay.style.display = "none";
      contactAction.style.display = "none";
      noContactNotice.style.display = "block";
    }

    // 3. Medical Alerts
    allergiesVal.textContent = data.allergies || "None reported";
    conditionsVal.textContent = data.medical_conditions || "None reported";

    // 4. Important Medications (Safe DOM construction)
    while (medicinesList.firstChild) {
      medicinesList.removeChild(medicinesList.firstChild);
    }

    const medicines = data.important_medicines || [];
    if (medicines.length > 0) {
      noMedicinesNotice.style.display = "none";
      medicinesList.style.display = "flex";

      medicines.forEach(function (med) {
        const itemEl = document.createElement("div");
        itemEl.className = "med-item";

        const titleEl = document.createElement("div");
        titleEl.className = "med-name";
        titleEl.textContent = med.dosage
          ? `${med.name} (${med.dosage})`
          : med.name;

        const subEl = document.createElement("div");
        subEl.className = "med-instructions";
        const parts = [];
        if (med.instruction) parts.push(med.instruction);
        if (med.scheduled_time) parts.push(`Time: ${med.scheduled_time}`);
        subEl.textContent = parts.length > 0 ? parts.join(" • ") : "As directed";

        itemEl.appendChild(titleEl);
        itemEl.appendChild(subEl);
        medicinesList.appendChild(itemEl);
      });
    } else {
      medicinesList.style.display = "none";
      noMedicinesNotice.style.display = "block";
    }

    // 5. Medical Reports (Safe DOM construction & strict HTTPS validation)
    while (reportsList.firstChild) {
      reportsList.removeChild(reportsList.firstChild);
    }

    const reports = data.medical_reports;
    if (reports === undefined) {
      // Localized error state: report retrieval failed or omitted
      reportsList.style.display = "none";
      noReportsNotice.style.display = "none";
      reportsErrorNotice.style.display = "block";
    } else if (Array.isArray(reports) && reports.length > 0) {
      reportsErrorNotice.style.display = "none";
      noReportsNotice.style.display = "none";
      reportsList.style.display = "flex";

      reports.forEach(function (report) {
        const itemEl = document.createElement("div");
        itemEl.className = "report-item";

        const leftCol = document.createElement("div");
        leftCol.className = "report-details";

        const titleEl = document.createElement("div");
        titleEl.className = "report-title";
        titleEl.textContent = report.title || "Medical Report";

        const metaEl = document.createElement("div");
        metaEl.className = "report-meta";
        const metaParts = [];
        if (report.lab_facility && report.lab_facility.trim().length > 0) {
          metaParts.push(report.lab_facility.trim());
        }
        if (report.report_date && report.report_date.trim().length > 0) {
          metaParts.push(report.report_date.trim());
        }
        const categoryBadge = getCategoryBadge(report.category);
        if (categoryBadge) {
          metaParts.push(categoryBadge);
        }
        metaEl.textContent =
          metaParts.length > 0 ? metaParts.join(" • ") : "Diagnostic Report";

        leftCol.appendChild(titleEl);
        leftCol.appendChild(metaEl);

        const rightCol = document.createElement("div");
        rightCol.className = "report-action";

        if (isValidHttpsUrl(report.view_url)) {
          const viewLink = document.createElement("a");
          viewLink.className = "btn-view-report";
          viewLink.textContent = "View Report";
          viewLink.href = report.view_url.trim();
          viewLink.target = "_blank";
          viewLink.rel = "noopener noreferrer";
          viewLink.setAttribute(
            "aria-label",
            "View report: " + (report.title || "Medical Report")
          );
          rightCol.appendChild(viewLink);
        } else {
          const unavailSpan = document.createElement("span");
          unavailSpan.className = "report-unavailable-badge";
          unavailSpan.textContent = "Unavailable";
          rightCol.appendChild(unavailSpan);
        }

        itemEl.appendChild(leftCol);
        itemEl.appendChild(rightCol);
        reportsList.appendChild(itemEl);
      });
    } else {
      reportsList.style.display = "none";
      reportsErrorNotice.style.display = "none";
      noReportsNotice.style.display = "block";
    }

    // 6. Timestamp
    if (data.updated_at) {
      try {
        const dateObj = new Date(data.updated_at);
        verificationTimestamp.textContent = `Last verified: ${dateObj.toLocaleDateString()} ${dateObj.toLocaleTimeString()}`;
      } catch (_) {
        verificationTimestamp.textContent = "";
      }
    } else {
      verificationTimestamp.textContent = "";
    }

    switchState("profile");
  }

  /**
   * Initializes the emergency profile lookup.
   */
  async function initEmergencyProfile() {
    const urlParams = new URLSearchParams(window.location.search);
    const token = (urlParams.get("token") || "").trim();

    if (!token) {
      renderError("missing_token");
      return;
    }

    // UUID v4 format verification (RFC 4122)
    const uuidRegex =
      /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
    if (!uuidRegex.test(token)) {
      renderError("invalid_token");
      return;
    }

    switchState("loading");

    try {
      const response = await fetch(
        `${API_ENDPOINT}?token=${encodeURIComponent(token)}&format=json`,
        {
          method: "GET",
          headers: {
            Accept: "application/json",
          },
        }
      );

      const result = await response.json().catch(function () {
        return null;
      });

      if (!response.ok) {
        if (response.status === 404) {
          renderError("inactive_token", result?.error);
        } else if (response.status === 400) {
          renderError("invalid_token", result?.error);
        } else {
          renderError("server_error", result?.error);
        }
        return;
      }

      if (!result || !result.data) {
        renderError("inactive_token");
        return;
      }

      renderProfile(result.data);
    } catch (err) {
      renderError(
        "server_error",
        "Network connection failed. Please check your mobile data/Wi-Fi connection."
      );
    }
  }

  // Start initialization on DOM load
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initEmergencyProfile);
  } else {
    initEmergencyProfile();
  }
})();
